### ISSUE TITLE
Add option to disable looped animations

### ISSUE THREAD

**Issue by min7-i** [m-i-n-a-r/birday#269]
Although I like the animations you integrated into the app, I feel that the repetition of the animations is more disruptive for me, especially the animated bird in the notification bar.

I'd prefer to not have any animated icons in my notification bar and although I'd like to keep the reminder for a birthday in the notifications I always remove it because the bird's animation is looped and doesn't stop.

Hence, I'd love to have an option to either disable the animation or at least disable the repetition.

**Comment by m-i-n-a-r** [comment]
That's a really specific issue! Just to make sure I understood: are you asking for an option to disable each and every animation, or just the notification icon?

**Comment by min7-i** [comment]
I guess implementing that option for all animations would require a lot of effort, so I'd already be content with an option to disable the animation for the notification icon.

**Comment by m-i-n-a-r** [comment]
Done in 7d3609347d7572338e8a6bbc27b02f0488a76609 but I still have to find a way to disable the animated notification icon. I'm on it.

**Comment by m-i-n-a-r** [comment]
Ok, done in 15e800f19add5b136070b48789e9c7cffb937362

**Comment by min7-i** [comment]
Great. I'm happy to see that you implemented this. Thanks 👍

**Comment by tadwohlrapp** [comment]
@m-i-n-a-r 
How exactly can the animated icon be disabled?
The only option I found which mentions animations is "Shimmer effect", which I turned off, but I still see confetti on start and the waving bird in my notifications.

**Comment by min7-i** [comment]
The current version 4.3.0 doesn't have a setting for this. The feature was only added recently, but there hasn't been a new release since then.

**Comment by m-i-n-a-r** [comment]
Yep, I still have to release it. I'm sorry :(
I'm doing my best to release a play store beta in the next few days!
